// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Simulations sidebar structure
  simulationsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generated from docs/simulations directory
    },
  ],
};

module.exports = sidebars;